export const dummyProducts = [
  {
    productID: 11111111,
    productName: "Canned Peaches",
    hasFlavors: true,
    flavors: ["flavor1", "flavor2", "flavor3"],
    description: "A delicious can of peaches that can last a long time.",
    imagePath: "/assets/dummies/canned_peaches.jpeg",
    price: 70.0,
  },
  {
    productID: 22222222,
    productName: "Canned Peaches",
    hasFlavors: true,
    flavors: ["flavor1", "flavor2", "flavor3"],
    description: "A delicious can of peaches that can last a long time.",
    imagePath: "/assets/dummies/canned_peaches.jpeg",
    price: 70.0,
  },
  {
    productID: 33333333,
    productName: "Canned Peaches",
    hasFlavors: true,
    flavors: ["flavor1", "flavor2", "flavor3"],
    description: "A delicious can of peaches that can last a long time.",
    imagePath: "/assets/dummies/canned_peaches.jpeg",
    price: 70.0,
  },
  {
    productID: 44444444,
    productName: "Canned Peaches",
    hasFlavors: true,
    flavors: ["flavor1", "flavor2", "flavor3"],
    description: "A delicious can of peaches that can last a long time.",
    imagePath: "/assets/dummies/canned_peaches.jpeg",
    price: 70.0,
  },
  {
    productID: 55555555,
    productName: "Canned Peaches",
    hasFlavors: true,
    flavors: ["flavor1", "flavor2", "flavor3"],
    description: "A delicious can of peaches that can last a long time.",
    imagePath: "/assets/dummies/canned_peaches.jpeg",
    price: 70.0,
  },
  {
    productID: 66666666,
    productName: "Canned Peaches",
    hasFlavors: true,
    flavors: ["flavor1", "flavor2", "flavor3"],
    description: "A delicious can of peaches that can last a long time.",
    imagePath: "/assets/dummies/canned_peaches.jpeg",
    price: 70.0,
  },
];

export const dummySearches = ["Peaches", "Beans", "Item", "ItemzzzzZZZZzzzzz"];
